-- Drop and recreate the public view to include business data while excluding personal contact info

DROP VIEW IF EXISTS public.annonces_public CASCADE;

CREATE VIEW public.annonces_public AS
SELECT 
  id,
  raison_sociale,  -- Company name (legal entity, not personal)
  siret,           -- Company registration number (public data)
  secteur_activite,
  annee_creation,
  departement,
  ville,
  code_postal,
  description_activite,
  specialites,
  certifications,
  type_clientele,
  zone_intervention,
  ca_n1,
  ca_n2,
  ca_n3,
  ebe_n1,
  resultat_net_n1,
  prix_vente,
  prix_negociable,
  marge_negociation,
  nombre_salaries,
  nombre_cdi,
  nombre_cdd,
  nombre_apprentis,
  anciennete_moyenne,
  competences_equipe,
  masse_salariale,
  accompagnement_vendeur,
  duree_accompagnement,
  situation_locaux,
  loyer_mensuel,
  duree_bail,
  surface_locaux,
  valeur_locaux,
  locaux_inclus_vente,
  materiel_principal,
  nombre_vehicules,
  valeur_materiel,
  etat_materiel,
  valeur_stock,
  valeur_portefeuille,
  site_web,
  nombre_clients_actifs,
  contrats_en_cours,
  marque_deposee,
  dettes_totales,
  dette_urssaf,
  dette_tva,
  dette_fournisseurs,
  dette_banques,
  credits_en_cours,
  montant_credits,
  credits_transferables,
  litiges_en_cours,
  nature_litiges,
  motif_vente,
  precisions_vente,
  atouts_principaux,
  potentiel_developpement,
  clientele_fidele_pct,
  reputation_locale,
  presence_digitale,
  elements_differenciants,
  type_transmission,
  accompagnement_propose,
  delai_vente,
  conditions_particulieres,
  niveau_anonymat,
  documents_disponibles,
  nda_requis,
  photos_entreprise,
  photos_materiel,
  photos_realisations,
  video_presentation,
  financement_bancaire,
  complement_vendeur,
  complement_vendeur_montant,
  complement_vendeur_duree,
  apport_requis,
  infos_complementaires,
  commentaires_acheteurs,
  visites_possibles,
  formule_abonnement,
  montant_abonnement,
  date_expiration,
  statut,
  nombre_vues,
  created_at,
  updated_at
FROM annonces
WHERE statut = 'publiee';

-- Grant access to anonymous and authenticated users
GRANT SELECT ON public.annonces_public TO anon;
GRANT SELECT ON public.annonces_public TO authenticated;

COMMENT ON VIEW public.annonces_public IS 'Public view of published listings. Excludes owner personal contact information (civilite, nom_prenom, email, telephone, preference_contact) but includes company data and business information.';